
    rsreset
STRUCT_C300_FIELD_00 rw 1 ; bg pal bank (lo)
STRUCT_C300_FIELD_02 rw 1 ; bg pal addr
STRUCT_C300_FIELD_04 rw 1 ; ob pal bank (lo)
STRUCT_C300_FIELD_06 rw 1 ; ob pal addr
STRUCT_C300_FIELD_08 rw 1 ; bank (lo)
STRUCT_C300_FIELD_0A rw 1 ; addr
STRUCT_C300_FIELD_0C rw 1 ; bank (lo)
STRUCT_C300_FIELD_0E rw 1 ; addr
STRUCT_C300_FIELD_10 rw 1 ; bank (lo)
STRUCT_C300_FIELD_12 rw 1 ; addr
STRUCT_C300_FIELD_14 rw 1 ; bank (lo)
STRUCT_C300_FIELD_16 rw 1 ; addr
STRUCT_C300_FIELD_18 rw 1 ; bank (lo)
STRUCT_C300_FIELD_1A rw 1 ; addr
STRUCT_C300_FIELD_1C rw 1 ; tile attr bank (lo)
STRUCT_C300_FIELD_1E rw 1 ; tile attr addr
STRUCT_C300_FIELD_20 rw 1 ; tile map bank (lo)
STRUCT_C300_FIELD_22 rw 1 ; tile map addr
STRUCT_C300_FIELD_24 rw 1 ; bank (lo)
STRUCT_C300_FIELD_26 rw 1 ; addr
STRUCT_C300_FIELD_28 rw 1 ; bank (lo)
STRUCT_C300_FIELD_2A rw 1 ; addr
STRUCT_C300_FIELD_2C rw 1 ; bank (lo)
STRUCT_C300_FIELD_2E rw 1 ; addr
STRUCT_C300_FIELD_30 rw 1 ; bank (lo)
STRUCT_C300_FIELD_32 rw 1 ; addr
STRUCT_C300_FIELD_34 rw 1 ; x offset?
STRUCT_C300_FIELD_36 rw 1 ; y offset?
STRUCT_C300_FIELD_38 rw 1
STRUCT_C300_FIELD_3A rw 1
STRUCT_C300_FIELD_3C rw 1
STRUCT_C300_PAD_3E   rb $40 - $3E
STRUCT_C300_SIZE     rb 0
